# Generated by Django 5.0.14 on 2025-12-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "For Sale"), ("rent", "For Rent")],
                default="sale",
                max_length=10,
            ),
        ),
    ]
