# Generated by Django 5.0.14 on 2025-12-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_latitude_property_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Prime Estate Agency", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text='Short catchy phrase (e.g., "Your Dream Home Awaits")',
                        max_length=255,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo",
                        null=True,
                        upload_to="company/",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Main hero/banner image for homepage and about page",
                        null=True,
                        upload_to="company/",
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True, help_text="Company story and background"
                    ),
                ),
                (
                    "mission",
                    models.TextField(blank=True, help_text="Mission statement"),
                ),
                ("vision", models.TextField(blank=True, help_text="Vision statement")),
                (
                    "email",
                    models.EmailField(default="hello@primeestate.com", max_length=254),
                ),
                ("phone", models.CharField(default="+1 (555) 000-0000", max_length=20)),
                (
                    "address",
                    models.CharField(
                        default="123 Market Street, Suite 400", max_length=255
                    ),
                ),
                ("city", models.CharField(default="Cityville", max_length=100)),
                ("state", models.CharField(default="ST", max_length=100)),
                ("postal_code", models.CharField(default="12345", max_length=10)),
                ("country", models.CharField(default="USA", max_length=100)),
                (
                    "office_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Office latitude for map display",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "office_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Office longitude for map display",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "business_hours",
                    models.TextField(
                        default="Mon-Fri: 9:00 AM - 6:00 PM\nSat: 10:00 AM - 4:00 PM\nSun: Closed"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year the company was founded", null=True
                    ),
                ),
                (
                    "total_properties_sold",
                    models.PositiveIntegerField(
                        default=0, help_text="Total properties sold (for statistics)"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=10, help_text="Years of experience (for statistics)"
                    ),
                ),
                (
                    "happy_clients",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Number of happy clients (for statistics)",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO meta description for homepage",
                        max_length=160,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
        ),
    ]
