# Generated by Django 5.0.14 on 2026-01-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_authorized",
            field=models.BooleanField(
                default=False,
                help_text="Agent must be authorized by admin to manage properties",
            ),
        ),
    ]
