# Generated by Django 6.0.5 on 2026-05-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_agent_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', '出售 / For Sale'), ('rent', '出租 / For Rent')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', '獨棟房屋 / House'), ('apartment', '公寓 / Apartment'), ('condo', '共管公寓 / Condo'), ('villa', '別墅 / Villa'), ('land', '土地 / Land')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', '可售 / Available'), ('pending', '待處理 / Pending'), ('sold', '已售出 / Sold')], default='available', max_length=20),
        ),
    ]
